add join code to email template and message url
OperationSpark/service-signups pull request #58
Opened 2023-01-31 22:04 UTC by taylorshephard

2023-01-31 22:29 UTC, harveysanders requested changes

2023-01-31 22:29 UTC, harveysanders commented on signup.go
> +		JoinCode             string `json:"joinCode"`
The CI tests are [failing](https://github.com/OperationSpark/service-signups/actions/runs/4058746074/jobs/6986038287#step:5:152).
This is due to adding this `JoinCode` field. If you decode the base64 you'll send the issue:
```javascript
JSON.parse(atob('eyJ0ZW1wbGF0ZSI6IkluZm9TZXNzaW9uIiwiem9vbUxpbmsiOiJodHRwczovL3VzMDZ3ZWIuem9vbS51cy9qLzEyMzQ1Njc4OTEwIiwiZGF0ZSI6IjIwMjItMTAtMDVUMTc6MDA6MDBaIiwibmFtZSI6IkZpcnN0TmFtZSIsImxvY2F0aW9uVHlwZSI6Ikh5YnJpZCIsImxvY2F0aW9uIjp7Im5hbWUiOiJTb21lIFBsYWNlIiwibGluZTEiOiIxMjMgTWFpbiBTdCIsImNpdHlTdGF0ZVppcCI6IkNpdHksIFN0YXRlIDEyMzQ1IiwibWFwVXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9tYXBzL3BsYWNlLzEyMytNYWluK1N0LCtDaXR5LCtTdGF0ZSsxMjM0NSJ9LCJqb2luQ29kZSI6IiJ9'))
```

```json
{
    "template": "InfoSession",
    "zoomLink": "https://us06web.zoom.us/j/12345678910",
    "date": "2022-10-05T17:00:00Z",
    "name": "FirstName",
    "locationType": "Hybrid",
    "location": {
        "name": "Some Place",
        "line1": "123 Main St",
        "cityStateZip": "City, State 12345",
        "mapUrl": "https://www.google.com/maps/place/123+Main+St,+City,+State+12345"
    },
    "joinCode": ""
}
```

So we can fix this in a few ways:
- update the struct tag to remove the field from the JSON if there is no value
  ```go
  JoinCode string `json:"joinCode,omitempty"`
  ```
- OR Update the expected base64 value in the test
- OR Add a JoinCode to the failing test _and_ update the expected base64 value

I'll let you choose which one you wanna go with

2023-02-01 01:46 UTC, harveysanders commented on signup.go
> +	if su.JoinCode != "" {
Since `p.JoinCode` is a string, it's [zero value](https://go.dev/tour/basics/12) is `""`. Given that, you can just add `JoinCode: su.JoinCode` directly in the params struct.

2023-02-01 16:29 UTC, taylorshephard commented on signup.go
> +	if su.JoinCode != "" {
okay i added it to the struct

2023-02-01 16:30 UTC, taylorshephard commented on signup.go
> +		JoinCode             string `json:"joinCode"`
okay I added omitempty to remove the field

2023-02-01 17:45 UTC, ptbarnum4 approved these changes

2023-02-01 17:53 UTC, harveysanders approved these changes

2023-02-01 18:11 UTC, merged