Support for auto enrollment
OperationSpark/service-signups pull request #64
Opened 2023-03-24 21:43 UTC by taylorshephard

2023-04-10 15:55 UTC, harveysanders requested changes

2023-04-10 15:55 UTC, harveysanders commented on greenlight/greenlight.go
```suggestion
// UnmarshalBSONValue unmarshals a Unix time (seconds after Jan 1, 1970 00:00 UTC) to `time.Time`. Fields using the UnixTime type were not serialized with the default Mongo ISODate so need custom marshaling/unmarshaling.
```

2023-04-10 15:55 UTC, harveysanders commented on signup.go
> +		GreenlightURL: fmt.Sprintf("https://greenlight.operationspark.org/sessions/%s/?subview=overview&userJoinCode=%s", su.SessionID, su.userJoinCode),
We should probably use an env var so that we can create URLs in any environment (local, testing, etc). We can add a parameter to this func.
```suggestion
		GreenlightURL: fmt.Sprintf("%s/sessions/%s/?subview=overview&userJoinCode=%s", greenlightHost, su.SessionID, su.userJoinCode),
```

2024-01-02 19:52 UTC, harveysanders commented on function.go
> +		log.Printf("Could not connect to MongoDB: %v\n", err)
It's probably best to not attempt to start the service if we can't connect to the database here
```suggestion
		log.Fatalf("Could not connect to MongoDB: %v\n", err)
```

2024-01-03 20:10 UTC, ptbarnum4 approved these changes
looks good! thought I approved this earlier

2024-01-03 20:33 UTC, harveysanders approved these changes

2024-01-03 20:33 UTC, merged